/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.ManageTheBusiness;

import TheBusiness.Business.Business;
import TheBusiness.MarketModel.Market;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author saatw
 */
public class UpsertMarketJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpsertMarketJPanel
     */
    
    private JPanel cardSequencePanel;
    private Market market;
    private Business business;

    public UpsertMarketJPanel(JPanel cardSequencePanel, Business business, Market market) {
        initComponents();
        this.cardSequencePanel = cardSequencePanel;
        this.market = market;
        this.business = business;
        if (!market.isAdd()) {
            btnSave.setEnabled(false);
            disableFields();
        } else {
            btnUpdate.setEnabled(false);
        }
        displayData();
    }

    public void disableFields()
    {
        txtMarketName.setEnabled(false);
        txtSubMarketName.setEnabled(false);
        txtCharacteristics.setEnabled(false);
        txtSubMarketType.setEnabled(false);
        txtSize.setEnabled(false);
        btnChannels.setEnabled(false);
    }
    
    public void displayData()
    {
        txtMarketName.setText(String.valueOf(market.getName()));
        txtSubMarketName.setText(market.getSubmarketName());
        txtCharacteristics.setText(market.getCharacteristics().stream().collect(Collectors.joining(",")));
        txtSubMarketType.setText(market.getSubmarketType());
        txtSize.setText(String.valueOf(market.getSize()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMarketName = new javax.swing.JLabel();
        lblCharacteristics = new javax.swing.JLabel();
        lblSubMarketName = new javax.swing.JLabel();
        lblSize = new javax.swing.JLabel();
        txtMarketName = new javax.swing.JTextField();
        txtCharacteristics = new javax.swing.JTextField();
        txtSubMarketType = new javax.swing.JTextField();
        txtSize = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        lblSubMarketType = new javax.swing.JLabel();
        btnChannels = new javax.swing.JButton();
        txtSubMarketName = new javax.swing.JTextField();
        lblChannels = new javax.swing.JLabel();

        lblMarketName.setText("Market Name:");

        lblCharacteristics.setText("Characteristics:");

        lblSubMarketName.setText("SubMarket Name:");

        lblSize.setText("Size:");

        txtMarketName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarketNameActionPerformed(evt);
            }
        });

        txtSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSizeActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lblSubMarketType.setText("SubMarket Type:");

        btnChannels.setText("Add/Update Channels");
        btnChannels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChannelsActionPerformed(evt);
            }
        });

        lblChannels.setText("Channels:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMarketName, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSubMarketName, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCharacteristics, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSize, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblChannels, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCharacteristics, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSize)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMarketName)
                                    .addComponent(txtSubMarketType)
                                    .addComponent(txtSubMarketName, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(btnChannels, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(18, 18, 18)
                        .addComponent(btnSave)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate))
                    .addComponent(lblSubMarketType, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(318, 318, 318))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarketName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMarketName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSubMarketType)
                    .addComponent(lblSubMarketName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubMarketType)
                    .addComponent(txtSubMarketName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCharacteristics, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCharacteristics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSize, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblChannels, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChannels))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSizeActionPerformed

    private void txtMarketNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarketNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarketNameActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        ManageMarketsJPanel manageMarketsPanel = new ManageMarketsJPanel(business, cardSequencePanel);

    // Remove the current panel and show the previous panel
    cardSequencePanel.removeAll();
    cardSequencePanel.add("ManageMarketsJPanel", manageMarketsPanel);
    ((CardLayout) cardSequencePanel.getLayout()).next(cardSequencePanel);
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
        txtMarketName.setEnabled(true);
        txtSubMarketName.setEnabled(true);
        txtSubMarketType.setEnabled(true);
        txtCharacteristics.setEnabled(true);
        txtSize.setEnabled(true);
        btnChannels.setEnabled(true);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
      if(!txtMarketName.getText().isEmpty() || !txtSubMarketName.getText().isEmpty() || !txtSubMarketType.getText().isEmpty() 
           || !txtCharacteristics.getText().isEmpty() || !txtSize.getText().isEmpty())
        {
            market.setName(txtMarketName.getText());
            Market subMarket = findMarketByName(txtSubMarketName.getText(), market.getSubmarkets());
            if (subMarket == null) {
                subMarket = new Market(txtSubMarketName.getText());
                market.addSubmarket(subMarket);
            }
            subMarket.setName(txtSubMarketName.getText());
            subMarket.setSubmarketType(txtSubMarketType.getText());
            
            market.setSubmarketType(txtSubMarketType.getText());
            market.setCharacteristics(new ArrayList<>(Arrays.asList(txtCharacteristics.getText().split(","))));
            market.setSize(Integer.parseInt(txtSize.getText()));
            
            if (market.isAdd()) {
               business.getMarketCatalog().addMarket(market);
               JOptionPane.showMessageDialog(null, "Market added successfully.","Information",JOptionPane.INFORMATION_MESSAGE);
            } else {
               JOptionPane.showMessageDialog(null, "Market updated successfully.","Information",JOptionPane.INFORMATION_MESSAGE);
            }
            
            txtMarketName.setText("");
            txtSubMarketName.setText("");
            txtSubMarketType.setText("");
            txtCharacteristics.setText("");
            txtSize.setText("");
            btnUpdate.setEnabled(true);
            btnSave.setEnabled(false);
            txtMarketName.setEnabled(true);
            txtSubMarketType.setEnabled(true);
            txtCharacteristics.setEnabled(true);
            txtSize.setEnabled(true);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please enter market fields.", "Warning", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnChannelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChannelsActionPerformed
        // TODO add your handling code here:
    ManageChannelsJPanel channelJPanel = new ManageChannelsJPanel(cardSequencePanel, business, market);
    cardSequencePanel.add("ManageChannelsJPanel", channelJPanel);
    CardLayout layout = (CardLayout)cardSequencePanel.getLayout();
    layout.next(cardSequencePanel);
    }//GEN-LAST:event_btnChannelsActionPerformed


      private  static Market findMarketByName(String marketName, ArrayList<Market> markets) {
    for (Market market : markets) {
        if (market.getName().equals(marketName)) {
            return market;
        }
    }
    return null; // Market not found
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnChannels;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblChannels;
    private javax.swing.JLabel lblCharacteristics;
    private javax.swing.JLabel lblMarketName;
    private javax.swing.JLabel lblSize;
    private javax.swing.JLabel lblSubMarketName;
    private javax.swing.JLabel lblSubMarketType;
    private javax.swing.JTextField txtCharacteristics;
    private javax.swing.JTextField txtMarketName;
    private javax.swing.JTextField txtSize;
    private javax.swing.JTextField txtSubMarketName;
    private javax.swing.JTextField txtSubMarketType;
    // End of variables declaration//GEN-END:variables
}
